[workspace]
members = [
    "rust/arcane_gfx",
    "rust/envmapgen",
    "rust/libc"
]

[profile.release]
debug = true
panic = "abort"

[profile.bench]
lto = true
debug = true

[patch.crates-io]
"libc" = { path = "rust/libc" }
"rand" = { path = "rust/rand" }
