[package]
name = "envmapgen"
version = "0.1.0"
authors = ["ARcane Developers"]

[lib]
crate-type = ["cdylib"]

[dependencies]
cgmath = "0.15.0"
lazy_static = "1.0.0"
arcane_gfx = { path = "../arcane_gfx" }
